### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by DenizGelion** [hanyaah/TkPublic#10]
Hey there my dude!
I downloaded your bot and wanted to host it on our server with a few subtle changes, I get an error when I try to start it with python3.5:

```
Traceback (most recent call last):
  File "TekkenBot.py", line 33, in <module>
    file = open('bot_settings.json', 'r+')
FileNotFoundError: [Errno 2] No such file or directory: 'bot_settings.json'
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7fec2ee998d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 93, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
```
There's supposed to be a bot_settings.json, but there's none here? If I were to create one, how would it looks like?

**Comment by DenizGelion** [comment]
Well, there was a part saying

#TODO: YOU LEFT OFF HERE
file = open('bot_settings.json', 'r+')

I deleted the line file= and it worked. The bot started, but seems heavily outdated in comparison to yours, that is running live. It seems to pull the data wrong. Can you update the project on Github please? Thank you very much!

**Comment by hanyaah** [comment]
Been forever, but I updated the repo, if it's still relevant to you.
